### ISSUE TITLE
Stack creation failure on Bastion Host

### ISSUE THREAD

**Issue by davpx** [splunk/splunk-aws-cloudformation#10]
Receiving the following error when using the master template. It fails and begins to rollback upon creating the bastion host.

Embedded stack arn:aws:cloudformation:us-west-2:429815655062:stack/splunk-cfn-test-BastionHost-1H10C7FAQK3H/7827fbc0-2763-11e5-b9e4-50442edf8e6e was not successfully created: The following resource(s) failed to create: [BastionSecurityGroup, CfnUser].

**Comment by rarsan** [comment]
@davpx , this likely happening because the user you're using to create cloudformation stacks may not have permissions to create these AWS resources, namely a security group and a user. Please try again with a user with such permissions such as an admin user.

**Comment by davpx** [comment]
@rarsan Thanks, permissions did seem to be the problem. Thanks for the great work you're doing here!
