### ISSUE TITLE
Failed on Creating DNS Records

### ISSUE THREAD

**Issue by Kevin-Manson** [splunk/splunk-aws-cloudformation#12]
Embedded stack arn:aws:cloudformation:us-east-1:975402726461:stack/SplunkTesting-SplunkCluster-1DNX0R34N3G89/cce69170-2fca-11e5-b106-500162a66cb4 was not successfully created: The following resource(s) failed to create: [MasterNodeInternalDNSRecord, SearchHeadDNSRecord, SearchHeadInternalDNSRecord, MasterNodeDNSRecord, PeerNodesDNSRecord].

I am using a subdomain like test.domain.com in route53. Any ideas on why i get this error.

**Comment by rarsan** [comment]
@Kevin-Manson, does the `HostedZoneName` param you specified correspond to a Hosted Zone that is already created in the same AWS account per [Route 53 docs](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingHostedZone.html).
For example, assuming domain.com already has a hosted zone created in AWS Route 53:
`HostedZoneName`: domain.com
`Subdomain`: test

**Comment by Kevin-Manson** [comment]
I think that was it, I was placing the whole domain in the HostedZoneName: test.domain.com and not splitting it out with HostedZoneName and Subdomain.  Trying to create again.

**Comment by rarsan** [comment]
Great.
