### ISSUE TITLE
Use noecho parameter on all password fields

### ISSUE THREAD

**Issue by halr9000** [splunk/splunk-aws-cloudformation#20]
As per http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#creds, use the `noecho` parameter for password entry fields.

**Comment by billbartlett** [comment]
Fixed in commit: https://github.com/splunk/splunk-aws-cloudformation/commit/e65aec73edd1f47039957ef5abc9d1319b98fa16#diff-d2c6142bb51a131775d42405979f0371
