### ISSUE TITLE
Use KeyPair parameter type for ease in data entry

### ISSUE THREAD

**Issue by halr9000** [splunk/splunk-aws-cloudformation#21]
As per CF docs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html, use the parameter type `AWS::EC2::KeyPair::KeyName` for ease in data entry.

**Comment by billbartlett** [comment]
Fixed in commit: https://github.com/splunk/splunk-aws-cloudformation/commit/e65aec73edd1f47039957ef5abc9d1319b98fa16#diff-d2c6142bb51a131775d42405979f0371
