### ISSUE TITLE
Stack creation failed because of initialization failure on SearchHead instance

### ISSUE THREAD

**Issue by roylai1224** [splunk/splunk-aws-cloudformation#7]
I tried to do a small deployment but was facing below issue. 100% repro.

17:39:55 UTC-0800	CREATE_FAILED	AWS::CloudFormation::WaitCondition	WaitCondition	WaitCondition received failed message: 'Failed to install chef' for uniqueId: i-5a698c57

17:39:56 UTC-0800	CREATE_FAILED	AWS::CloudFormation::Stack	Splunk-SplunkCluster-178XH8XYUAIWW-SearchHead-1NGS2V2AKY9TW	The following resource(s) failed to create: [WaitCondition].

Is this related to a recent bug fix?
                "#install chef without docs\n",
                "gem install ohai --version 6.16.0 --no-ri --no-rdoc || error_exit 'Failed to install ohai'\n",
                "gem install chef --version 10.24.0 --no-ri --no-rdoc || error_exit 'Failed to install chef'\n"

**Comment by henrysher** [comment]
i have patched the template to directly use ruby 2.0, the latest ohai and chef. It works.

**Comment by ccummings1** [comment]
i still see this error

**Comment by rarsan** [comment]
As pointed out by @henrysher , this was a matter of using ruby2, and updating chef & ohai.
I've updated splunk_server cfn template accordingly and pushed it out to public S3 bucket for consumption.

**Comment by rarsan** [comment]
Thanks everyone. Closing.
