### ISSUE TITLE
Support multi-AZ

### ISSUE THREAD

**Issue by dmourati** [splunk/splunk-aws-cloudformation#8]
Nice work. Here's a feature request to make this better still by supporting multiple availability zones.

**Comment by rarsan** [comment]
Multi-AZ support is now added!
Using `ClusterAZCount` parameter, you can now have splunk indexer cluster deployed across 1, 2 or 3 AZs.
Using `ClusterSize` parameter, you can still set number of peer nodes which will be evenly distributed across the different AZs. For example, when `ClusterAZCount=3`, and `ClusterSize=6`, there will be 3 AZs each of which will have 2 peers nodes, for a total of 6 peer nodes.
Thanks for the feature request. Keep'em coming. Closing..

**Comment by dmourati** [comment]
Sweet! Thanks @rarsan!
